/* The following code was generated by JFlex 1.6.1 */

package lexico;
import static lexico.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/lexico/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\22\1\12\1\24\1\24\1\23\22\0\1\22\1\26\1\10"+
    "\2\17\1\27\1\32\1\11\1\27\1\27\1\21\1\26\1\27\1\16"+
    "\1\3\1\20\1\2\1\62\1\65\1\64\1\66\1\67\1\63\1\2"+
    "\1\61\1\2\1\27\1\35\1\30\1\34\1\31\1\27\1\17\6\4"+
    "\11\1\1\56\12\1\1\27\1\13\1\27\1\27\2\17\1\36\1\42"+
    "\1\47\1\37\1\6\1\53\1\55\1\5\1\51\1\1\1\45\1\44"+
    "\1\52\1\14\1\43\1\54\1\1\1\40\1\41\1\15\1\50\1\57"+
    "\1\60\1\7\1\46\1\70\1\27\1\33\1\27\1\27\6\17\1\25"+
    "\u1e6e\17\u0134\0\1\24\1\24\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\1\3\1\4\2\2\2\1\1\5\1\2"+
    "\12\4\17\2\1\6\1\3\1\6\5\2\1\0\1\3"+
    "\1\1\2\2\1\3\1\1\1\5\1\1\1\2\1\7"+
    "\41\2\1\1\1\3\1\1\1\7\4\2\1\3\1\0"+
    "\2\2\1\5\1\1\21\2\1\7\15\2\1\10\2\1"+
    "\2\2\2\11\1\1\3\2\1\12\7\2\1\7\1\12"+
    "\2\2\1\7\14\2\1\0\2\1\1\0\2\1\1\2"+
    "\4\11\1\3\32\2\1\0\1\13\1\1\1\13\1\3"+
    "\1\0\1\13\1\1\1\13\1\3\1\2\1\3\1\0"+
    "\1\11\1\0\1\1\1\0\1\1\1\2\1\7\12\2"+
    "\2\13\1\2\1\0\2\11\4\2\1\11\6\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\u01c8\0\71\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u01c8"+
    "\0\u031e\0\u0357\0\u0390\0\u03c9\0\71\0\u0402\0\u043b\0\u0474"+
    "\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c"+
    "\0\u0675\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804"+
    "\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u01c8\0\u095a\0\u0993"+
    "\0\u09cc\0\u0a05\0\344\0\u0a3e\0\u0a77\0\u0ab0\0\162\0\u0ae9"+
    "\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1"+
    "\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79"+
    "\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041"+
    "\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209"+
    "\0\u1242\0\u127b\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398"+
    "\0\71\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527"+
    "\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef"+
    "\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845\0\u187e\0\u18b7"+
    "\0\u18f0\0\u1929\0\u1962\0\u199b\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f"+
    "\0\u1ab8\0\u1af1\0\u1b2a\0\u1b63\0\u1b9c\0\162\0\u1bd5\0\u1c0e"+
    "\0\u1c47\0\u1c80\0\u1cb9\0\u1cf2\0\u1d2b\0\u1d64\0\u1d9d\0\u1dd6"+
    "\0\162\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65"+
    "\0\u1f9e\0\u1fd7\0\u2010\0\u2049\0\u2082\0\u20bb\0\u20f4\0\u212d"+
    "\0\u2166\0\u219f\0\u21d8\0\u2211\0\u224a\0\u2283\0\u22bc\0\u22f5"+
    "\0\u232e\0\u2367\0\u23a0\0\u23d9\0\u2412\0\u244b\0\u2484\0\u24bd"+
    "\0\u24f6\0\u252f\0\u2568\0\u25a1\0\u25da\0\u2613\0\u264c\0\u2685"+
    "\0\u26be\0\u26f7\0\u2730\0\u2769\0\u27a2\0\u2082\0\u27db\0\u2814"+
    "\0\u284d\0\u2886\0\u28bf\0\u28f8\0\u2931\0\u296a\0\u29a3\0\u29dc"+
    "\0\u2a15\0\u2a4e\0\u2a87\0\u2ac0\0\u2af9\0\u2b32\0\u2b6b\0\u2ba4"+
    "\0\u2367\0\u2bdd\0\u23a0\0\u23a0\0\u2c16\0\u2412\0\u2c4f\0\u244b"+
    "\0\u244b\0\u2c88\0\u2cc1\0\u2cfa\0\u2d33\0\u2cc1\0\u25da\0\u2d6c"+
    "\0\u2da5\0\u2dde\0\u140a\0\u2e17\0\u2e50\0\u2e89\0\u2ec2\0\u2efb"+
    "\0\u2f34\0\u2f6d\0\u2fa6\0\u2fdf\0\u3018\0\71\0\u01c8\0\u3051"+
    "\0\u308a\0\u30c3\0\u30fc\0\u3135\0\u316e\0\u31a7\0\u31e0\0\u3219"+
    "\0\u3252\0\u328b\0\u32c4\0\u32fd\0\u3336\0\u336f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\3"+
    "\1\10\1\11\1\12\1\11\1\3\1\13\1\14\1\11"+
    "\1\15\1\16\2\12\1\0\1\11\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\17\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\3\3\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\3\1\42\1\43\1\44\7\4\1\3"+
    "\72\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\1\45\1\4"+
    "\1\46\2\45\1\47\1\45\2\11\1\0\1\11\2\45"+
    "\4\11\3\0\10\11\1\0\23\45\7\4\1\45\1\0"+
    "\1\11\1\46\7\11\1\0\7\11\3\0\10\11\1\0"+
    "\23\11\7\46\1\11\1\0\2\3\1\11\2\3\1\50"+
    "\1\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\5\3\1\51\25\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\1\52\1\53\4\11\3\0\10\11"+
    "\1\0\6\3\1\54\24\3\1\55\7\10\1\56\1\10"+
    "\1\0\1\57\6\10\3\55\10\10\1\55\33\10\1\0"+
    "\11\11\1\0\7\11\3\0\10\11\1\0\33\11\1\0"+
    "\2\3\1\11\1\3\1\60\2\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\2\3\1\61\30\3"+
    "\1\0\1\11\1\62\1\63\6\11\1\0\7\11\3\0"+
    "\7\11\1\20\1\0\23\11\7\62\1\11\1\0\11\11"+
    "\1\0\5\11\1\64\1\65\3\0\7\11\1\20\1\0"+
    "\33\11\1\0\11\11\1\0\6\11\1\20\3\0\7\11"+
    "\1\20\1\0\33\11\1\0\11\11\1\0\7\11\3\0"+
    "\7\11\1\20\1\0\33\11\1\0\11\11\1\0\7\11"+
    "\3\0\3\11\1\20\3\11\1\20\1\0\33\11\1\0"+
    "\11\11\1\0\7\11\3\0\4\11\1\20\2\11\1\20"+
    "\1\0\33\11\1\0\11\11\1\0\7\11\3\0\5\11"+
    "\1\20\2\11\1\0\33\11\1\0\11\11\1\0\7\11"+
    "\3\0\6\11\1\20\1\11\1\0\33\11\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\1\3\1\66\1\3\1\67\27\3\1\0"+
    "\2\3\1\11\2\3\1\70\1\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\1\71\4\3\1\67"+
    "\25\3\1\0\2\3\1\11\2\3\1\72\1\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\2\3\1\73\1\3\2\11\1\0"+
    "\1\11\1\3\1\74\4\11\3\0\10\11\1\0\5\3"+
    "\1\75\24\3\1\76\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\77"+
    "\1\3\1\100\2\3\1\101\2\3\1\102\22\3\1\0"+
    "\2\3\1\11\2\3\1\103\1\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\33\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\1\104\4\3\1\105\25\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\13\3\1\106\1\3\1\107\15\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\110\1\3"+
    "\4\11\3\0\10\11\1\0\14\3\1\111\1\67\15\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\1\112\4\3\1\113\5\3"+
    "\1\114\17\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\1\115\1\3"+
    "\1\116\2\3\1\117\4\3\1\120\1\121\17\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\1\122\1\3\1\123\7\3\1\124"+
    "\20\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\2\3\1\125\30\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\1\117\12\3\1\126\17\3"+
    "\1\0\2\3\1\11\1\3\1\127\1\130\1\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\1\45\2\11\4\45\2\11\1\0\1\11\2\45"+
    "\4\11\3\0\10\11\1\0\23\45\7\11\1\45\1\0"+
    "\1\11\1\46\3\11\1\131\3\11\1\0\7\11\3\0"+
    "\10\11\1\0\23\11\7\46\1\11\1\0\1\45\1\132"+
    "\1\11\4\45\2\11\1\0\1\11\2\45\1\133\3\11"+
    "\3\0\10\11\1\0\23\45\7\132\1\45\1\0\2\3"+
    "\1\11\3\3\1\134\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\33\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\12\3\1\135\20\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\12\3"+
    "\1\136\20\3\1\0\2\3\1\11\1\3\1\137\2\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\33\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\3\3\1\140\27\3"+
    "\10\55\1\141\1\55\1\0\1\142\55\55\1\0\7\11"+
    "\1\10\1\11\1\0\3\10\4\11\3\0\10\11\1\0"+
    "\33\11\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\13\3\1\143\17\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\1\144\11\3\1\140\20\3"+
    "\1\0\1\11\1\62\1\46\2\11\1\131\3\11\1\0"+
    "\7\11\3\0\10\11\1\0\23\11\7\62\1\11\1\145"+
    "\11\64\1\0\7\64\1\145\2\0\1\11\7\64\1\145"+
    "\33\64\1\0\11\11\1\0\6\11\1\146\3\0\10\11"+
    "\1\0\33\11\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\1\3\1\147"+
    "\31\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\6\3\1\150\24\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\10\3\1\151\22\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\3\1\152"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\1\153\1\3\4\11\3\0"+
    "\10\11\1\0\11\3\1\154\21\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\2\3\1\155\30\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\6\3\1\156\24\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\157"+
    "\32\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\6\3\1\160\24\3"+
    "\1\0\2\3\1\11\2\3\1\161\1\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\5\3\1\162\25\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\1\3\1\163\4\11"+
    "\3\0\10\11\1\0\33\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\1\135\32\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\6\3\1\164"+
    "\24\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\1\165\1\3\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\166\1\3"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\13\3\1\167\17\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\1\3\1\170\4\11\3\0\10\11"+
    "\1\0\33\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\16\3\1\171"+
    "\14\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\16\3\1\172\14\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\1\3\1\173\31\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\174\1\3"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\6\3\1\54\24\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\5\3\1\136\25\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\2\3"+
    "\1\67\30\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\1\175\1\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\1\176"+
    "\1\3\4\11\3\0\10\11\1\0\33\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\10\3\1\177\22\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\13\3\1\200\17\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\4\3\1\201\26\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\202"+
    "\32\3\1\0\2\3\1\11\2\3\1\203\1\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\13\3\1\204\17\3\1\0"+
    "\2\3\1\11\2\3\1\205\1\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\13\3\1\206\17\3"+
    "\1\0\1\11\1\132\7\11\1\0\3\11\1\133\3\11"+
    "\3\0\10\11\1\0\23\11\7\132\1\11\1\0\1\11"+
    "\1\132\7\11\1\0\7\11\3\0\10\11\1\0\23\11"+
    "\7\132\1\11\1\0\2\3\1\11\4\3\1\207\1\210"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\2\3\1\151\30\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\14\3\1\67\16\3\1\0\2\3"+
    "\1\11\2\3\1\211\1\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\2\3\1\67\1\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\33\3\10\0\1\55\2\0\3\55"+
    "\54\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\3\3\1\67\27\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\212\1\3"+
    "\4\11\3\0\10\11\1\0\33\3\12\145\1\0\10\145"+
    "\3\0\43\145\1\213\11\146\1\214\6\146\1\215\3\213"+
    "\10\146\1\213\33\146\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\2\3"+
    "\1\216\30\3\1\0\2\3\1\11\2\3\1\217\1\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\33\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\3\3\1\206\27\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\12\3\1\220\20\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\1\3\1\221\31\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\5\3\1\222\25\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\12\3\1\223\1\224\17\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\13\3\1\225\17\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\4\3\1\226\26\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\227"+
    "\32\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\1\230\32\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\6\3\1\67\24\3\1\0\2\3"+
    "\1\11\2\3\1\231\1\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\6\3\1\232\24\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\1\3\1\233\4\11\3\0\10\11"+
    "\1\0\3\3\1\234\27\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\1\3\1\235\4\11\3\0\10\11"+
    "\1\0\33\3\1\0\2\3\1\11\3\3\1\236\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\2\3\1\237\1\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\5\3\1\240\25\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\16\3\1\241\14\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\13\3\1\242\17\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\12\3\1\243\20\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\11\3"+
    "\1\244\21\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\1\245\1\3\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\1\246\32\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\21\3\1\247\11\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\6\3\1\250\24\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\17\3\1\251\13\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\22\3"+
    "\1\67\10\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\6\3\1\140"+
    "\24\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\7\3\1\151\23\3"+
    "\1\252\1\253\1\254\1\253\1\254\1\253\1\254\3\253"+
    "\1\252\7\253\3\252\10\253\1\252\2\254\2\253\1\254"+
    "\4\253\1\254\3\253\1\254\5\253\7\254\1\253\1\255"+
    "\1\256\1\257\1\256\1\257\1\256\1\257\3\256\1\255"+
    "\7\256\3\255\10\256\1\255\2\257\2\256\1\257\4\256"+
    "\1\257\3\256\1\257\5\256\7\257\1\256\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\2\3\1\206\30\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\3\3\1\260\27\3\12\213\1\214\6\213\1\261"+
    "\47\213\12\262\1\263\5\262\1\0\1\261\1\264\46\262"+
    "\1\213\11\146\1\214\5\146\1\265\1\215\3\213\10\146"+
    "\1\213\33\146\1\0\2\3\1\11\2\3\1\266\1\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\33\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\1\3\1\140\4\11\3\0\10\11\1\0\17\3\1\267"+
    "\13\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\2\3\1\270\30\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\1\271"+
    "\1\3\4\11\3\0\10\11\1\0\33\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\11\3\1\272\21\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\1\273\1\3\4\11\3\0"+
    "\10\11\1\0\33\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\3"+
    "\1\274\31\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\5\3\1\206"+
    "\25\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\1\275\1\3\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\7\3\1\67\23\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\3\3\1\276\27\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\11\3\1\277\21\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\2\3\1\300\10\3\1\301\17\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\1\3\1\302\4\11\3\0"+
    "\10\11\1\0\33\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\23\3"+
    "\1\67\1\303\1\304\1\305\1\306\3\3\1\0\2\3"+
    "\1\11\2\3\1\307\1\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\2\3\1\310\30\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\2\3\1\272\30\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\13\3"+
    "\1\224\17\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\15\3\1\311"+
    "\15\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\1\3\1\312\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\3\1\313"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\2\3\1\314\1\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\33\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\4\3\1\204\26\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\315"+
    "\32\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\13\3\1\316\17\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\14\3\1\317\16\3\2\252"+
    "\1\320\1\252\1\320\1\252\1\320\1\252\1\321\25\252"+
    "\2\320\2\252\1\320\4\252\1\320\3\252\1\320\5\252"+
    "\7\320\2\252\1\253\1\322\1\253\1\322\1\253\1\322"+
    "\1\253\1\323\1\253\1\252\7\253\3\252\10\253\1\252"+
    "\2\322\2\253\1\322\4\253\1\322\3\253\1\322\5\253"+
    "\7\322\1\253\1\252\1\253\1\254\1\253\1\254\1\253"+
    "\1\254\1\253\1\324\1\253\1\252\7\253\3\252\10\253"+
    "\1\252\2\254\2\253\1\254\4\253\1\254\3\253\1\254"+
    "\5\253\7\254\1\253\2\255\1\325\1\255\1\325\1\255"+
    "\1\325\2\255\1\326\24\255\2\325\2\255\1\325\4\255"+
    "\1\325\3\255\1\325\5\255\7\325\2\255\1\256\1\327"+
    "\1\256\1\327\1\256\1\327\2\256\1\330\1\255\7\256"+
    "\3\255\10\256\1\255\2\327\2\256\1\327\4\256\1\327"+
    "\3\256\1\327\5\256\7\327\1\256\1\255\1\256\1\257"+
    "\1\256\1\257\1\256\1\257\2\256\1\331\1\255\7\256"+
    "\3\255\10\256\1\255\2\257\2\256\1\257\4\256\1\257"+
    "\3\256\1\257\5\256\7\257\1\256\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\15\3\1\332\15\3\12\213\1\214\5\213\1\333"+
    "\1\261\47\213\12\262\1\263\6\262\1\263\1\262\3\334"+
    "\55\262\1\263\5\262\1\335\1\263\1\262\3\334\55\262"+
    "\1\263\5\262\1\334\1\261\1\264\46\262\1\336\11\337"+
    "\1\340\6\337\1\341\3\336\10\337\1\336\33\337\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\3\3\1\143\27\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\1\342\32\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\1\343\1\3\4\11\3\0\10\11"+
    "\1\0\33\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\1\3\1\151"+
    "\31\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\1\3\1\67\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\17\3\1\67\13\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\13\3\1\344\17\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\11\3\1\345\21\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\5\3\1\346\25\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\1\223"+
    "\32\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\1\347\1\3\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\2\3\1\350\30\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\25\3\1\67\1\3\1\351\3\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\30\3\1\67\2\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\27\3\1\67\3\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\31\3\1\352\1\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\1\3\1\67\31\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\1\353\1\3\4\11\3\0\10\11\1\0"+
    "\33\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\13\3\1\354\17\3"+
    "\1\0\2\3\1\11\2\3\1\151\1\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\33\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\13\3\1\355\17\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\10\3\1\206\22\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\1\3\1\140\4\11\3\0"+
    "\10\11\1\0\33\3\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\11\3"+
    "\1\67\21\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\1\67\32\3"+
    "\2\0\1\320\1\0\1\320\1\0\1\320\1\0\1\356"+
    "\25\0\2\320\2\0\1\320\4\0\1\320\3\0\1\320"+
    "\5\0\7\320\2\0\1\11\1\322\1\11\1\322\1\11"+
    "\1\322\1\11\1\357\1\11\1\0\7\11\3\0\10\11"+
    "\1\0\2\322\2\11\1\322\4\11\1\322\3\11\1\322"+
    "\5\11\7\322\1\11\2\0\1\325\1\0\1\325\1\0"+
    "\1\325\2\0\1\356\24\0\2\325\2\0\1\325\4\0"+
    "\1\325\3\0\1\325\5\0\7\325\2\0\1\11\1\327"+
    "\1\11\1\327\1\11\1\327\2\11\1\357\1\0\7\11"+
    "\3\0\10\11\1\0\2\327\2\11\1\327\4\11\1\327"+
    "\3\11\1\327\5\11\7\327\1\11\1\0\2\3\1\11"+
    "\2\3\1\360\1\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\33\3\12\336\1\340\6\336\1\361"+
    "\47\336\12\334\1\362\6\334\1\363\47\334\23\335\3\0"+
    "\43\335\21\0\1\361\1\340\46\0\1\336\11\337\1\340"+
    "\5\337\1\265\1\341\3\336\10\337\1\336\33\337\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\3\1\364"+
    "\4\11\3\0\10\11\1\0\33\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\1\3\1\365\4\11\3\0"+
    "\10\11\1\0\33\3\1\0\2\3\1\11\2\3\1\221"+
    "\1\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\33\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\1\3\1\345"+
    "\31\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\12\3\1\140\20\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\12\3\1\366\20\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\2\3\4\11"+
    "\3\0\10\11\1\0\23\3\1\67\7\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\25\3\1\67\5\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\1\162\32\3\1\0\2\3\1\11\2\3\1\117"+
    "\1\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\33\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\2\3\4\11\3\0\10\11\1\0\5\3\1\367"+
    "\25\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\2\3\1\221\30\3"+
    "\12\336\1\340\5\336\1\333\1\361\47\336\12\334\1\362"+
    "\5\334\1\0\1\363\1\370\60\334\1\362\5\334\1\0"+
    "\1\363\47\334\1\0\2\3\1\11\2\3\1\371\1\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\33\3\1\0\2\3\1\11\4\3\2\11\1\0\1\11"+
    "\2\3\4\11\3\0\10\11\1\0\10\3\1\67\22\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\11\3\1\372\21\3\1\0"+
    "\2\3\1\11\4\3\2\11\1\0\1\11\1\67\1\3"+
    "\4\11\3\0\10\11\1\0\33\3\12\334\1\362\6\334"+
    "\1\363\1\370\46\334\1\0\2\3\1\11\4\3\2\11"+
    "\1\0\1\11\2\3\4\11\3\0\10\11\1\0\11\3"+
    "\1\373\21\3\1\0\2\3\1\11\4\3\2\11\1\0"+
    "\1\11\1\3\1\374\4\11\3\0\10\11\1\0\33\3"+
    "\1\0\2\3\1\11\4\3\2\11\1\0\1\11\2\3"+
    "\4\11\3\0\10\11\1\0\1\375\32\3\1\0\2\3"+
    "\1\11\4\3\2\11\1\0\1\11\2\3\4\11\3\0"+
    "\10\11\1\0\5\3\1\117\25\3\1\0\2\3\1\11"+
    "\4\3\2\11\1\0\1\11\2\3\4\11\3\0\10\11"+
    "\1\0\6\3\1\376\24\3\1\0\2\3\1\11\4\3"+
    "\2\11\1\0\1\11\2\3\4\11\3\0\10\11\1\0"+
    "\6\3\1\221\24\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13224];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\7\1\1\11\12\1\1\11\27\1\1\0"+
    "\63\1\1\11\1\0\107\1\1\0\2\1\1\0\42\1"+
    "\1\0\4\1\1\0\6\1\1\0\1\1\1\0\1\1"+
    "\1\0\15\1\1\11\2\1\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 202) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext()+" "+(yyline+1);return ERROR_CARACTERES_NO_VALIDOS;
            }
          case 12: break;
          case 2: 
            { lexeme=yytext()+" "+(yyline+1); return IDENTIFICADOR;
            }
          case 13: break;
          case 3: 
            { lexeme=yytext()+" "+(yyline+1); return LITERAL;
            }
          case 14: break;
          case 4: 
            { lexeme=yytext()+" "+(yyline+1); return OPERADOR;
            }
          case 15: break;
          case 5: 
            { /* ignore */
            }
          case 16: break;
          case 6: 
            { lexeme=yytext()+" "+(yyline+1);return ERROR_IDENTIFICADOR;
            }
          case 17: break;
          case 7: 
            { lexeme=yytext()+" "+(yyline+1); return PALABRA_RESERVADA;
            }
          case 18: break;
          case 8: 
            { lexeme=yytext()+" "+(yyline+1); return UNIDAD;
            }
          case 19: break;
          case 9: 
            { lexeme=yytext()+" "+(yyline+1);return ERROR_COMENTARIO;
            }
          case 20: break;
          case 10: 
            { lexeme=yytext()+" "+(yyline+1); return TRANSAC;
            }
          case 21: break;
          case 11: 
            { lexeme=yytext()+" "+(yyline+1);return ERROR_HEXADECIMAL;
            }
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
