/* The following code was generated by JFlex 1.6.1 */

package lexico;
import static lexico.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/lexico/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\14\1\3\1\4\1\4\1\3\22\0\1\14\1\16\1\11"+
    "\2\0\1\17\1\22\1\12\1\17\1\17\1\24\1\16\1\17\1\13"+
    "\1\17\1\15\1\2\1\54\1\57\1\56\1\60\1\61\1\55\1\2"+
    "\1\53\1\2\1\17\1\17\1\20\1\25\1\21\1\17\1\0\6\5"+
    "\11\1\1\50\12\1\1\17\1\0\1\17\1\17\1\5\1\0\1\26"+
    "\1\32\1\40\1\27\1\7\1\45\1\47\1\6\1\43\1\1\1\35"+
    "\1\34\1\44\1\41\1\33\1\46\1\1\1\30\1\31\1\37\1\42"+
    "\1\51\1\52\1\10\1\36\1\62\1\17\1\23\1\17\1\17\6\0"+
    "\1\4\u1fa2\0\1\4\1\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\2\1\5\1\4"+
    "\10\5\20\2\1\3\2\2\1\3\5\2\1\0\1\3"+
    "\1\5\1\4\1\5\1\2\1\6\43\2\1\0\1\2"+
    "\1\3\1\6\4\2\2\3\23\2\1\6\15\2\1\7"+
    "\2\0\5\2\1\10\6\2\1\6\1\2\1\10\2\2"+
    "\1\6\14\2\2\0\32\2\1\3\1\2\1\6\26\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\63\0\u0198\0\u01cb\0\63\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f"+
    "\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7"+
    "\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f"+
    "\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u07f8\0\u085e\0\314\0\u0891"+
    "\0\u0660\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6"+
    "\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26"+
    "\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe"+
    "\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056"+
    "\0\u1089\0\u10bc\0\u10ef\0\u1122\0\u07f8\0\u0fbd\0\u1155\0\u1188"+
    "\0\u11bb\0\u11ee\0\u1221\0\u1254\0\u1287\0\u12ba\0\u12ed\0\u1320"+
    "\0\u1353\0\u1386\0\u13b9\0\u13ec\0\u141f\0\u1452\0\u1485\0\u14b8"+
    "\0\u14eb\0\u151e\0\u1551\0\u1584\0\u15b7\0\u15ea\0\u161d\0\u1650"+
    "\0\u1683\0\u16b6\0\u16e9\0\u171c\0\u174f\0\u1782\0\u17b5\0\u0660"+
    "\0\u17e8\0\u181b\0\u184e\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u0660"+
    "\0\u194d\0\u1980\0\u19b3\0\u19e6\0\u1a19\0\u1a4c\0\u1a7f\0\u1ab2"+
    "\0\u1ae5\0\u1b18\0\u1b4b\0\u1b7e\0\u1bb1\0\u1be4\0\u1c17\0\u1c4a"+
    "\0\u1c7d\0\u1cb0\0\u1ce3\0\u1d16\0\u1d49\0\u1d7c\0\u1daf\0\u1de2"+
    "\0\u1e15\0\u1e48\0\u1e7b\0\u1eae\0\u1ee1\0\u1f14\0\u1f47\0\u1f7a"+
    "\0\u1fad\0\u1fe0\0\u2013\0\u2046\0\u2079\0\u20ac\0\u20df\0\u2112"+
    "\0\u2145\0\u2178\0\u21ab\0\u21de\0\u2211\0\u2244\0\u2277\0\u22aa"+
    "\0\u22dd\0\u2310\0\u2343\0\u2376\0\314\0\u23a9\0\u13ec\0\u23dc"+
    "\0\u240f\0\u2442\0\u2475\0\u24a8\0\u24db\0\u250e\0\u2541\0\u2574"+
    "\0\u25a7\0\u25da\0\u260d\0\u2640\0\u2673\0\u26a6\0\u26d9\0\u270c"+
    "\0\u273f\0\u2772\0\u27a5\0\u27d8\0\u280b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\0\1\3\1\6\1\7"+
    "\1\3\2\2\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\13\1\22\1\23\1\24"+
    "\1\25\1\26\3\3\1\27\1\30\1\31\1\3\1\32"+
    "\1\33\1\34\1\35\1\36\1\3\1\37\1\40\1\41"+
    "\7\4\1\3\2\0\1\42\50\0\7\42\2\0\1\43"+
    "\1\44\2\0\4\43\15\0\25\43\7\44\1\43\2\42"+
    "\1\45\2\0\46\42\7\45\1\42\64\0\1\43\1\44"+
    "\2\0\2\43\1\46\1\43\15\0\5\43\1\47\17\43"+
    "\7\44\1\43\1\0\1\43\1\44\2\0\4\43\15\0"+
    "\6\43\1\50\2\43\1\51\1\43\1\52\11\43\7\44"+
    "\1\43\2\53\1\54\2\0\20\53\1\55\25\53\7\54"+
    "\1\53\2\0\1\42\12\0\1\56\7\0\1\57\25\0"+
    "\7\42\3\0\1\42\22\0\1\57\25\0\7\42\3\0"+
    "\1\42\15\0\1\57\4\0\1\57\25\0\7\42\3\0"+
    "\1\42\16\0\1\57\3\0\1\57\25\0\7\42\3\0"+
    "\1\42\17\0\1\57\30\0\7\42\3\0\1\42\20\0"+
    "\1\57\27\0\7\42\3\0\1\42\21\0\2\57\25\0"+
    "\7\42\2\0\1\43\1\44\2\0\4\43\15\0\1\43"+
    "\1\60\1\43\1\61\21\43\7\44\1\43\1\0\1\43"+
    "\1\44\2\0\2\43\1\62\1\43\15\0\1\63\4\43"+
    "\1\61\17\43\7\44\1\43\1\0\1\43\1\44\2\0"+
    "\2\43\1\64\1\43\15\0\25\43\7\44\1\43\1\0"+
    "\1\43\1\44\2\0\2\43\1\65\1\43\15\0\5\43"+
    "\1\66\3\43\1\67\13\43\7\44\1\70\1\0\1\43"+
    "\1\44\2\0\4\43\15\0\1\71\1\43\1\72\2\43"+
    "\1\73\2\43\1\74\14\43\7\44\1\43\1\0\1\43"+
    "\1\44\2\0\2\43\1\75\1\43\15\0\25\43\7\44"+
    "\1\43\1\0\1\43\1\44\2\0\1\43\1\76\2\43"+
    "\15\0\2\43\1\77\22\43\7\44\1\43\1\0\1\43"+
    "\1\44\2\0\4\43\15\0\1\100\4\43\1\101\17\43"+
    "\7\44\1\43\1\0\1\43\1\44\2\0\4\43\15\0"+
    "\15\43\1\102\1\43\1\103\5\43\7\44\1\43\1\0"+
    "\1\43\1\44\2\0\4\43\15\0\13\43\1\104\2\43"+
    "\1\105\1\61\5\43\7\44\1\43\1\0\1\43\1\44"+
    "\2\0\4\43\15\0\1\106\4\43\1\107\7\43\1\110"+
    "\7\43\7\44\1\43\1\0\1\43\1\44\2\0\4\43"+
    "\15\0\1\111\1\43\1\112\2\43\1\113\6\43\1\114"+
    "\1\115\7\43\7\44\1\43\1\0\1\43\1\44\2\0"+
    "\4\43\15\0\1\116\1\43\1\117\11\43\1\120\10\43"+
    "\7\44\1\43\1\0\1\43\1\44\2\0\4\43\15\0"+
    "\2\43\1\121\22\43\7\44\1\43\1\0\1\43\1\44"+
    "\2\0\4\43\15\0\1\113\14\43\1\122\7\43\7\44"+
    "\1\43\1\0\1\43\1\44\2\0\1\43\1\123\1\124"+
    "\1\43\15\0\25\43\7\44\1\43\2\0\1\42\4\0"+
    "\1\125\43\0\7\42\2\0\2\43\2\0\4\43\15\0"+
    "\35\43\1\0\1\43\1\44\2\0\2\43\1\126\1\43"+
    "\15\0\25\43\7\44\1\43\2\42\1\45\2\0\2\42"+
    "\1\127\43\42\7\45\1\42\1\0\2\43\2\0\3\43"+
    "\1\130\15\0\35\43\1\0\2\43\2\0\4\43\15\0"+
    "\14\43\1\131\20\43\1\0\2\43\2\0\4\43\15\0"+
    "\3\43\1\132\31\43\1\0\2\43\2\0\1\43\1\133"+
    "\2\43\15\0\35\43\1\0\2\43\2\0\4\43\15\0"+
    "\14\43\1\134\20\43\2\0\1\135\50\0\7\135\1\0"+
    "\2\135\1\54\2\0\2\135\1\136\43\135\7\54\1\135"+
    "\3\56\2\0\56\56\1\0\2\43\2\0\4\43\15\0"+
    "\1\43\1\137\33\43\1\0\2\43\2\0\4\43\15\0"+
    "\6\43\1\140\26\43\1\0\2\43\2\0\4\43\15\0"+
    "\10\43\1\141\24\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\142\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\12\43\1\143\1\144\21\43\1\0\2\43\2\0\4\43"+
    "\15\0\6\43\1\145\26\43\1\0\2\43\2\0\4\43"+
    "\15\0\2\43\1\146\32\43\1\0\2\43\2\0\4\43"+
    "\15\0\1\147\34\43\1\0\2\43\2\0\4\43\15\0"+
    "\6\43\1\150\26\43\1\0\2\43\2\0\2\43\1\151"+
    "\1\43\15\0\35\43\1\0\2\43\2\0\4\43\15\0"+
    "\5\43\1\152\27\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\153\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\131\34\43\1\0\2\43\2\0\4\43\15\0\15\43"+
    "\1\154\17\43\1\0\2\43\2\0\4\43\15\0\1\155"+
    "\13\43\1\132\20\43\1\0\2\43\2\0\4\43\15\0"+
    "\6\43\1\156\26\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\157\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\160\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\15\43\1\161\17\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\162\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\20\43\1\163\14\43\1\0\2\43\2\0\4\43\15\0"+
    "\20\43\1\164\14\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\43\1\165\33\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\166\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\6\43\1\50\26\43\1\0\2\43\2\0\4\43\15\0"+
    "\5\43\1\134\27\43\1\0\2\43\2\0\4\43\15\0"+
    "\2\43\1\61\32\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\167\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\170\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\10\43\1\171\24\43\1\0\2\43\2\0\4\43\15\0"+
    "\15\43\1\172\17\43\1\0\2\43\2\0\4\43\15\0"+
    "\4\43\1\173\30\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\174\34\43\1\0\2\43\2\0\2\43\1\175\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\4\43\15\0\15\43"+
    "\1\176\17\43\1\0\2\43\2\0\2\43\1\177\1\43"+
    "\15\0\15\43\1\200\17\43\2\0\1\135\10\0\1\53"+
    "\37\0\7\135\2\0\2\43\2\0\4\43\2\0\1\53"+
    "\12\0\35\43\2\0\1\42\4\0\1\125\3\0\1\53"+
    "\37\0\7\42\2\0\2\43\2\0\4\43\1\201\1\202"+
    "\13\0\35\43\1\0\2\43\2\0\4\43\15\0\2\43"+
    "\1\141\32\43\1\0\2\43\2\0\2\43\1\61\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\2\43\1\203\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\4\43\15\0\16\43"+
    "\1\61\16\43\1\0\2\43\2\0\4\43\15\0\2\43"+
    "\1\204\32\43\1\0\2\43\2\0\2\43\1\205\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\4\43\15\0\3\43"+
    "\1\200\31\43\1\0\2\43\2\0\4\43\15\0\14\43"+
    "\1\206\20\43\1\0\2\43\2\0\4\43\15\0\5\43"+
    "\1\207\27\43\1\0\2\43\2\0\4\43\15\0\1\43"+
    "\1\210\33\43\1\0\2\43\2\0\4\43\15\0\15\43"+
    "\1\211\17\43\1\0\2\43\2\0\4\43\15\0\14\43"+
    "\1\212\1\213\17\43\1\0\2\43\2\0\4\43\15\0"+
    "\4\43\1\214\30\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\215\34\43\1\0\2\43\2\0\4\43\15\0\1\216"+
    "\34\43\1\0\2\43\2\0\4\43\15\0\6\43\1\61"+
    "\26\43\1\0\2\43\2\0\2\43\1\217\1\43\15\0"+
    "\35\43\1\0\2\43\2\0\4\43\15\0\3\43\1\61"+
    "\31\43\1\0\2\43\2\0\4\43\15\0\13\43\1\220"+
    "\21\43\1\0\2\43\2\0\4\43\15\0\6\43\1\221"+
    "\26\43\1\0\2\43\2\0\4\43\15\0\3\43\1\222"+
    "\5\43\1\223\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\224\23\43\1\0\2\43\2\0\3\43\1\225"+
    "\15\0\35\43\1\0\2\43\2\0\2\43\1\226\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\4\43\15\0\5\43"+
    "\1\227\27\43\1\0\2\43\2\0\4\43\15\0\20\43"+
    "\1\230\14\43\1\0\2\43\2\0\4\43\15\0\15\43"+
    "\1\231\17\43\1\0\2\43\2\0\4\43\15\0\14\43"+
    "\1\232\20\43\1\0\2\43\2\0\4\43\15\0\12\43"+
    "\1\233\22\43\1\0\2\43\2\0\4\43\15\0\13\43"+
    "\1\234\21\43\1\0\2\43\2\0\4\43\15\0\1\235"+
    "\34\43\1\0\2\43\2\0\4\43\15\0\23\43\1\236"+
    "\11\43\1\0\2\43\2\0\4\43\15\0\6\43\1\237"+
    "\26\43\1\0\2\43\2\0\4\43\15\0\21\43\1\240"+
    "\13\43\1\0\2\43\2\0\4\43\15\0\24\43\1\61"+
    "\10\43\1\0\2\43\2\0\4\43\15\0\6\43\1\132"+
    "\26\43\1\0\2\43\2\0\4\43\15\0\7\43\1\141"+
    "\25\43\2\0\1\241\2\0\1\241\1\0\1\241\16\0"+
    "\2\241\2\0\1\241\5\0\1\241\4\0\1\241\5\0"+
    "\7\241\3\0\1\242\2\0\1\242\1\0\1\242\16\0"+
    "\2\242\2\0\1\242\5\0\1\242\4\0\1\242\5\0"+
    "\7\242\2\0\2\43\2\0\4\43\15\0\2\43\1\200"+
    "\32\43\1\0\2\43\2\0\2\43\1\243\1\43\15\0"+
    "\35\43\1\0\2\43\2\0\4\43\15\0\11\43\1\132"+
    "\7\43\1\244\13\43\1\0\2\43\2\0\4\43\15\0"+
    "\2\43\1\245\32\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\246\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\43\1\247\33\43\1\0\2\43\2\0\4\43\15\0"+
    "\12\43\1\250\22\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\251\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\5\43\1\200\27\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\252\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\7\43\1\61\25\43\1\0\2\43\2\0\4\43\15\0"+
    "\3\43\1\224\31\43\1\0\2\43\2\0\4\43\15\0"+
    "\3\43\1\253\31\43\1\0\2\43\2\0\4\43\15\0"+
    "\12\43\1\254\22\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\255\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\2\43\1\256\12\43\1\257\17\43\1\0\2\43\2\0"+
    "\4\43\15\0\25\43\1\61\1\260\1\261\1\262\1\263"+
    "\3\43\1\0\2\43\2\0\2\43\1\264\1\43\15\0"+
    "\35\43\1\0\2\43\2\0\4\43\15\0\2\43\1\265"+
    "\32\43\1\0\2\43\2\0\4\43\15\0\2\43\1\250"+
    "\32\43\1\0\2\43\2\0\4\43\15\0\15\43\1\213"+
    "\17\43\1\0\2\43\2\0\4\43\15\0\17\43\1\266"+
    "\15\43\1\0\2\43\2\0\4\43\15\0\11\43\1\267"+
    "\23\43\1\0\2\43\2\0\4\43\15\0\11\43\1\270"+
    "\23\43\1\0\2\43\2\0\2\43\1\271\1\43\15\0"+
    "\35\43\1\0\2\43\2\0\4\43\15\0\4\43\1\176"+
    "\30\43\1\0\2\43\2\0\4\43\15\0\1\272\34\43"+
    "\1\0\2\43\2\0\4\43\15\0\15\43\1\273\17\43"+
    "\1\0\2\43\2\0\4\43\15\0\16\43\1\274\16\43"+
    "\2\0\1\241\2\0\1\241\1\0\1\241\1\0\1\275"+
    "\14\0\2\241\2\0\1\241\5\0\1\241\4\0\1\241"+
    "\5\0\7\241\3\0\1\242\2\0\1\242\1\0\1\242"+
    "\2\0\1\275\13\0\2\242\2\0\1\242\5\0\1\242"+
    "\4\0\1\242\5\0\7\242\2\0\2\43\2\0\4\43"+
    "\15\0\3\43\1\154\31\43\1\0\2\43\2\0\4\43"+
    "\15\0\1\276\34\43\1\0\2\43\2\0\4\43\15\0"+
    "\13\43\1\277\21\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\43\1\141\33\43\1\0\2\43\2\0\4\43\15\0"+
    "\15\43\1\300\17\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\61\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\21\43\1\61\13\43\1\0\2\43\2\0\4\43\15\0"+
    "\12\43\1\301\22\43\1\0\2\43\2\0\4\43\15\0"+
    "\17\43\1\302\15\43\1\0\2\43\2\0\4\43\15\0"+
    "\5\43\1\303\27\43\1\0\2\43\2\0\4\43\15\0"+
    "\2\43\1\304\32\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\212\34\43\1\0\2\43\2\0\4\43\15\0\13\43"+
    "\1\305\21\43\1\0\2\43\2\0\4\43\15\0\27\43"+
    "\1\61\1\43\1\306\3\43\1\0\2\43\2\0\4\43"+
    "\15\0\32\43\1\61\2\43\1\0\2\43\2\0\4\43"+
    "\15\0\31\43\1\61\3\43\1\0\2\43\2\0\4\43"+
    "\15\0\33\43\1\307\1\43\1\0\2\43\2\0\4\43"+
    "\15\0\1\43\1\61\33\43\1\0\2\43\2\0\4\43"+
    "\15\0\13\43\1\310\21\43\1\0\2\43\2\0\4\43"+
    "\15\0\15\43\1\311\17\43\1\0\2\43\2\0\2\43"+
    "\1\141\1\43\15\0\35\43\1\0\2\43\2\0\4\43"+
    "\15\0\15\43\1\312\17\43\1\0\2\43\2\0\4\43"+
    "\15\0\10\43\1\200\24\43\1\0\2\43\2\0\4\43"+
    "\15\0\11\43\1\132\23\43\1\0\2\43\2\0\4\43"+
    "\15\0\12\43\1\61\22\43\1\0\2\43\2\0\4\43"+
    "\15\0\1\61\34\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\313\23\43\1\0\2\43\2\0\4\43\15\0"+
    "\11\43\1\314\23\43\1\0\2\43\2\0\2\43\1\210"+
    "\1\43\15\0\35\43\1\0\2\43\2\0\2\43\1\315"+
    "\1\43\15\0\35\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\43\1\301\33\43\1\0\2\43\2\0\4\43\15\0"+
    "\14\43\1\316\20\43\1\0\2\43\2\0\4\43\15\0"+
    "\14\43\1\132\20\43\1\0\2\43\2\0\4\43\15\0"+
    "\25\43\1\61\7\43\1\0\2\43\2\0\4\43\15\0"+
    "\27\43\1\61\5\43\1\0\2\43\2\0\4\43\15\0"+
    "\1\152\34\43\1\0\2\43\2\0\2\43\1\113\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\4\43\15\0\5\43"+
    "\1\317\27\43\1\0\2\43\2\0\2\43\1\320\1\43"+
    "\15\0\35\43\1\0\2\43\2\0\4\43\15\0\10\43"+
    "\1\61\24\43\1\0\2\43\2\0\4\43\15\0\2\43"+
    "\1\210\32\43\1\0\2\43\2\0\4\43\15\0\12\43"+
    "\1\321\22\43\1\0\2\43\2\0\4\43\15\0\13\43"+
    "\1\61\21\43\1\0\2\43\2\0\4\43\15\0\12\43"+
    "\1\322\22\43\1\0\2\43\2\0\4\43\15\0\11\43"+
    "\1\323\23\43\1\0\2\43\2\0\4\43\15\0\1\324"+
    "\34\43\1\0\2\43\2\0\4\43\15\0\5\43\1\113"+
    "\27\43\1\0\2\43\2\0\4\43\15\0\6\43\1\325"+
    "\26\43\1\0\2\43\2\0\4\43\15\0\6\43\1\210"+
    "\26\43";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10302];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\1\1\11\45\1\1\0\3\1\1\11\45\1"+
    "\1\0\53\1\2\0\36\1\2\0\32\1\1\11\30\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 202) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            }
          case 9: break;
          case 2: 
            { lexeme=yytext()+" "+(yyline+1); return IDENTIFICADOR;
            }
          case 10: break;
          case 3: 
            { lexeme=yytext()+" "+(yyline+1);return LITERAL;
            }
          case 11: break;
          case 4: 
            { /* ignore */
            }
          case 12: break;
          case 5: 
            { lexeme=yytext()+" "+(yyline+1); return OPERADOR;
            }
          case 13: break;
          case 6: 
            { lexeme=yytext()+" "+(yyline+1); return PALABRA_RESERVADA;
            }
          case 14: break;
          case 7: 
            { lexeme=yytext()+" "+(yyline+1); return UNIDAD;
            }
          case 15: break;
          case 8: 
            { lexeme=yytext()+" "+(yyline+1); return TRANSAC;
            }
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
