
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 22 07:52:58 CST 2020
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 14;
  public static final int ERROR_IDENTIFICADOR = 51;
  public static final int Coma = 34;
  public static final int Llave_c = 20;
  public static final int Op_booleano = 16;
  public static final int Llave_a = 19;
  public static final int Caret = 35;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int ERROR_STRING = 54;
  public static final int TRANSAC = 48;
  public static final int Dos_Puntos = 11;
  public static final int Else = 7;
  public static final int Visibilidad = 44;
  public static final int Break = 38;
  public static final int Enum = 28;
  public static final int Corchete_c = 22;
  public static final int Returns = 42;
  public static final int Corchete_a = 21;
  public static final int Punto = 36;
  public static final int Op_Aritmetico = 43;
  public static final int Return = 41;
  public static final int Pragma = 29;
  public static final int While = 9;
  public static final int ERROR_HEXADECIMAL = 57;
  public static final int Cadena = 5;
  public static final int Parentesis_c = 18;
  public static final int Parentesis_a = 17;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int P_coma = 24;
  public static final int Function = 32;
  public static final int error = 1;
  public static final int Solidity = 30;
  public static final int Contract = 27;
  public static final int Linea = 2;
  public static final int PALABRA_RESERVADA = 46;
  public static final int Op_atribucion = 15;
  public static final int ERROR = 58;
  public static final int Do = 8;
  public static final int Continue = 39;
  public static final int Modificador = 33;
  public static final int Op_logico = 13;
  public static final int UNIDAD = 47;
  public static final int OPERADOR = 55;
  public static final int String = 40;
  public static final int ERROR_CARACTERES_NO_VALIDOS = 50;
  public static final int Identificador = 25;
  public static final int Struct = 31;
  public static final int ERROR_COMENTARIO = 56;
  public static final int STRING = 53;
  public static final int Pregunta = 45;
  public static final int Numero = 26;
  public static final int Main = 23;
  public static final int ERROR_NOTACION_CIENTIFICA = 52;
  public static final int This = 37;
  public static final int Igual = 12;
  public static final int ERROR_CEROS_A_LA_IZQUIERDA = 49;
  public static final int Comillas = 3;
}

