
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 10 01:16:34 CST 2020
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 18;
  public static final int NUMERO = 48;
  public static final int ERROR_IDENTIFICADOR = 47;
  public static final int Coma = 39;
  public static final int Llave_c = 25;
  public static final int Op_booleano = 21;
  public static final int Llave_a = 24;
  public static final int If = 7;
  public static final int T_dato = 4;
  public static final int ERROR_STRING = 51;
  public static final int Else = 8;
  public static final int Enum = 33;
  public static final int Corchete_c = 27;
  public static final int Corchete_a = 26;
  public static final int Op_Aritmetico = 44;
  public static final int Return = 43;
  public static final int Pragma = 34;
  public static final int While = 10;
  public static final int Division = 16;
  public static final int Int = 5;
  public static final int ERROR_HEXADECIMAL = 54;
  public static final int Cadena = 6;
  public static final int Parentesis_c = 23;
  public static final int Parentesis_a = 22;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int P_coma = 29;
  public static final int Function = 37;
  public static final int Solidity = 35;
  public static final int error = 1;
  public static final int Contract = 32;
  public static final int Linea = 2;
  public static final int Tipo = 42;
  public static final int Op_atribucion = 19;
  public static final int ERROR = 55;
  public static final int Do = 9;
  public static final int Modificador = 38;
  public static final int Op_logico = 17;
  public static final int OPERADOR = 52;
  public static final int Visibildad = 40;
  public static final int String = 41;
  public static final int ERROR_CARACTERES_NO_VALIDOS = 46;
  public static final int Identificador = 30;
  public static final int Struct = 36;
  public static final int Resta = 14;
  public static final int ERROR_COMENTARIO = 53;
  public static final int STRING = 50;
  public static final int Multiplicacion = 15;
  public static final int Op_incremento = 20;
  public static final int Numero = 31;
  public static final int Suma = 13;
  public static final int Main = 28;
  public static final int ERROR_NOTACION_CIENTIFICA = 49;
  public static final int Igual = 12;
  public static final int ERROR_CEROS_A_LA_IZQUIERDA = 45;
  public static final int Comillas = 3;
}

